### ISSUE TITLE
Feature Request: Support aranès

### ISSUE THREAD

**Issue by didILeaveTheStoveOn** [adriacabeza/DeepCatalan#1]
Hi, this looks really cool! I was wondering if you could add support for [aranès](https://ca.wikipedia.org/wiki/Aran%C3%A8s), as the language already has over 5k speakers and it would probably prove useful to a non-neglectable subset of them. 

Thanks for making this!

**Comment by adriacabeza** [comment]
Hi @lacadev !! I'm really glad that you like the project. 
If I do have time I might look into that possibility. However, it seems that it would be pretty difficult because of the lack of datasets. Anyway, if you want to contribute and start developing it, go for it 🚀!

**Comment by didILeaveTheStoveOn** [comment]
Thanks for the quick reply @adriacabeza . Glad to know you're open to having this implemented!
I'll definitely look into it when I get some free time. Closing this until then, cheers!
